builds:
  - main: ./cli
    id: "cli"
    binary: ./bin/autoproxy
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=vendor

  - main: ./daemon
    id: "daemon"
    binary: ./bin/autoproxyd
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=vendor

checksum:
  name_template: "checksums.txt"

nfpms:
  - package_name: iitj-autoproxy
    vendor: XanderWatson
    homepage: https://github.com/XanderWatson/iitj-autoproxy
    maintainer: Saahil Bhavsar <saahil_bhavsar@outlook.com>
    license: MIT
    formats:
      - deb
      - archlinux
    release: "1"
    bindir: /usr
    contents:
      - src: LICENSE
        dst: /usr/share/licenses/iitj-autoproxy/LICENSE
      - src: README.md
        dst: /usr/share/doc/iitj-autoproxy/README.md
      - src: base_config.json
        dst: /etc/iitj-autoproxy/autoproxy.config
      - src: ./scripts/linux/login.sh
        dst: /usr/bin/autoproxylogin
      - src: ./scripts/linux/daemon-start.sh
        dst: /usr/bin/autoproxyd-start
      - src: ./scripts/linux/daemon-stop.sh
        dst: /usr/bin/autoproxyd-stop
    scripts:
      postinstall: ./scripts/linux/daemon-start.sh

release:
  prerelease: auto
  github:
    owner: XanderWatson
    name: iitj-autoproxy
  name_template: "{{.ProjectName}}-v{{.Version}}"
  extra_files:
    - glob: ./base_config.json

aurs:
  - name: iitj-autoproxy-bin
    homepage: https://github.com/XanderWatson/iitj-autoproxy
    license: MIT
    maintainers:
      - "Saahil Bhavsar <saahil_bhavsar@outlook.com>"
    contributors:
      - "Saahil Bhavsar <saahil_bhavsar@outlook.com>"
    commit_author:
      name: XanderWatson
      email: saahil_bhavsar@outlook.com
    private_key: "{{ .Env.AUR_KEY }}"
    git_url: "ssh://aur@aur.archlinux.org/iitj-autoproxy-bin.git"
    package: |-
      install -Dm755 "./bin/autoproxyd" "${pkgdir}/usr/bin/autoproxyd"
      install -Dm755 "./bin/autoproxy" "${pkgdir}/usr/bin/autoproxy"
      install -Dm755 "/usr/bin/autoproxylogin" "${pkgdir}/usr/bin/autoproxylogin"
      install -Dm755 "/usr/bin/autoproxyd-start" "${pkgdir}/usr/bin/autoproxyd-start"
      install -Dm755 "/usr/bin/autoproxyd-stop" "${pkgdir}/usr/bin/autoproxyd-stop"
      install -Dm644 "/usr/share/licenses/iitj-autoproxy/LICENSE" "${pkgdir}/usr/share/licenses/iitj-autoproxy/LICENSE"
      install -Dm644 "/etc/iitj-autoproxy/autoproxy.config" "${pkgdir}/etc/iitj-autoproxy/autoproxy.config"
      install -Dm644 "/usr/share/doc/iitj-autoproxy/README.md" "${pkgdir}/usr/share/doc/iitj-autoproxy/README.md"
