builds:
  - main: ./cli
    id: "cli"
    binary: ./bin/autoproxy
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=1
      - >-
        {{- if eq .Os "darwin" }}
          {{- if eq .Arch "amd64"}}CC=o64-clang{{- end }}
          {{- if eq .Arch "arm64"}}CC=aarch64-apple-darwin20.2-clang{{- end }}
        {{- end }}
        {{- if eq .Os "windows" }}
          {{- if eq .Arch "amd64" }}CC=x86_64-w64-mingw32-gcc{{- end }}
        {{- end }}
    flags:
      - -mod=vendor
    ignore:
      - goos: windows
        goarch: arm64
      - goos: darwin
        goarch: amd64

  - main: ./daemon
    id: "daemon"
    binary: ./bin/autoproxyd
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=1
      - >-
        {{- if eq .Os "darwin" }}
          {{- if eq .Arch "amd64"}}CC=o64-clang{{- end }}
          {{- if eq .Arch "arm64"}}CC=aarch64-apple-darwin20.2-clang{{- end }}
        {{- end }}
        {{- if eq .Os "windows" }}
          {{- if eq .Arch "amd64" }}CC=x86_64-w64-mingw32-gcc{{- end }}
        {{- end }}
    flags:
      - -mod=vendor
    ignore:
      - goos: windows
        goarch: arm64
      - goos: darwin
        goarch: amd64

checksum:
  name_template: "checksums.txt"

nfpms:
  - package_name: iitj-autoproxy
    vendor: XanderWatson
    homepage: https://github.com/XanderWatson/iitj-autoproxy
    maintainer: Saahil Bhavsar <saahil_bhavsar@outlook.com>
    license: MIT
    formats:
      - deb
      - archlinux
    release: "1"
    bindir: /usr
    contents:
      - src: LICENSE
        dst: /usr/share/licenses/iitj-autoproxy/LICENSE
      - src: README.md
        dst: /usr/share/doc/iitj-autoproxy/README.md
      - src: autoproxy.config
        dst: /etc/iitj-autoproxy/autoproxy.config
      - src: ./scripts/linux/login.sh
        dst: /usr/bin/autoproxylogin
      - src: ./scripts/linux/daemon-start.sh
        dst: /usr/bin/autoproxyd-start
      - src: ./scripts/linux/daemon-stop.sh
        dst: /usr/bin/autoproxyd-stop
    scripts:
      postinstall: ./scripts/linux/daemon-start.sh

release:
  prerelease: auto
  github:
    owner: XanderWatson
    name: iitj-autoproxy
  name_template: "{{.ProjectName}}-v{{.Version}}"
  extra_files:
    - glob: autoproxy.config

aurs:
  - name: iitj-autoproxy-bin
    homepage: https://github.com/XanderWatson/iitj-autoproxy
    license: MIT
    maintainers:
      - "Saahil Bhavsar <saahil_bhavsar@outlook.com>"
    contributors:
      - "Saahil Bhavsar <saahil_bhavsar@outlook.com>"
    commit_author:
      name: XanderWatson
      email: saahil_bhavsar@outlook.com
    private_key: "{{ .Env.AUR_KEY }}"
    git_url: "ssh://aur@aur.archlinux.org/iitj-autoproxy-bin.git"
    package: |-
      install -Dm755 "./bin/autoproxyd" "${pkgdir}/usr/bin/autoproxyd"
      install -Dm755 "./bin/autoproxy" "${pkgdir}/usr/bin/autoproxy"
      install -Dm755 "./scripts/linux/login.sh" "${pkgdir}/usr/bin/autoproxylogin"
      install -Dm755 "./scripts/linux/daemon-start.sh" "${pkgdir}/usr/bin/autoproxyd-start"
      install -Dm755 "./scripts/linux/daemon-stop.sh" "${pkgdir}/usr/bin/autoproxyd-stop"
      install -Dm644 "./LICENSE" "${pkgdir}/usr/share/licenses/iitj-autoproxy/LICENSE"
      install -Dm644 "./autoproxy.config" "${pkgdir}/etc/iitj-autoproxy/autoproxy.config"
      install -Dm644 "./README.md" "${pkgdir}/usr/share/doc/iitj-autoproxy/README.md"

# chocolateys:
#   - name: iitj-autoproxy
#     owners: Saahil Bhavsar
#     title: IITJ Autoproxy
#     authors: Saahil Bhavsar
#     project_url: https://github.com/XanderWatson/iitj-autoproxy
#     url_template: "https://github.com/XanderWatson/iitj-autoproxy/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
#     copyright: 2023 Saahil Bhavsar
#     license_url: https://github.com/XanderWatson/iitj-autoproxy/blob/main/LICENSE
#     require_license_acceptance: false
#     project_source_url: https://github.com/XanderWatson/iitj-autoproxy
#     docs_url: https://github.com/XanderWatson/iitj-autoproxy/blob/main/README.md
#     bug_tracker_url: https://github.com/XanderWatson/iitj-autoproxy/issues
#     summary: A CLI tool to automatically login to IIT Jodhpur's network firewall.
#     description: |
#       IITJ Autoproxy installer package.
#       A CLI tool to automatically login to IIT Jodhpur's network firewall.
#     release_notes: "https://github.com/XanderWatson/iitj-autoproxy/releases/tag/v{{ .Version }}"
#     api_key: '{{ .Env.CHOCOLATEY_API_KEY }}'
#     source_repo: "https://push.chocolatey.org/"
#     skip_publish: false

archives:
  - wrap_in_directory: false
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md
      - autoproxy.config
      - scripts/*
      - install.ps1
      - autoproxy-uninstall.ps1

brews:
  - name: iitj-autoproxy
    url_template: "https://github.com/XanderWatson/iitj-autoproxy/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    download_strategy: CurlDownloadStrategy
    commit_author:
      name: XanderWatson
      email: saahil_bhavsar@outlook.com
    commit_msg_template: "Brew formula update for iitj-autoproxy version {{ .Tag }}"
    caveats: "How to use this binary"
    homepage: "https://github.com/XanderWatson/iitj-autoproxy"
    description: "A CLI tool to automatically login to IIT Jodhpur's network firewall."
    license: "MIT"
    skip_upload: false
    install: |
      bin.install "bin/autoproxy"
      bin.install "bin/autoproxyd"
    post_install: |
        etc.install "autoproxy.config"
        etc.install "LICENSE"
        etc.install "README.md"
    repository:
      owner: XanderWatson
      name: homebrew-iitj-autoproxy
      branch: main
      pull_request:
        enabled: false
