name: goreleaser

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - uses: actions/setup-go@v3
        with:
          go-version: ">=1.20.2"
          cache: true
      - uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: ${{ env.GITHUB_REF_NAME }}
          args: release --clean --config=.goreleaser.yml
        env:
          GITHUB_TOKEN: ${{ secrets.PUBLISHER_TOKEN }}
          AUR_KEY: ${{ secrets.AUR_KEY }}

  goreleaser-darwin:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup cross-compilation environment
        run: |
            sudo apt-get update
            sudo apt-get install -y clang gcc-multilib g++-multilib
      - run: git fetch --force --tags
      - uses: actions/setup-go@v3
        with:
          go-version: ">=1.20.2"
          cache: true
      - uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: ${{ env.GITHUB_REF_NAME }}
          args: release --clean --config=darwin.goreleaser.yml
        env:
          GITHUB_TOKEN: ${{ secrets.PUBLISHER_TOKEN }}
          AUR_KEY: ${{ secrets.AUR_KEY }}
